[package]
author = "Akshat Shukla"
name = "b64-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
b64 = { path="../../" }
clap = {version = "4.4.3", features = ["derive"]}

